package model;
// Generated Sep 25, 2020 2:37:57 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name = "message",
         catalog = "onlineschooldb"
)
public class Message implements java.io.Serializable {

    private Integer id;
    private String content;
    private Teacher messageFrom;
    private Student messageTo;
    private Date sendtime;
    private String status;

    public Message() {
    }

    public Message(String content, Teacher messageFrom, Student messageTo, Date sendtime, String status) {
        this.content = content;
        this.messageFrom = messageFrom;
        this.messageTo = messageTo;
        this.sendtime = sendtime;
        this.status = status;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "content")
    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "message_from")
    public Teacher getMessageFrom() {
        return this.messageFrom;
    }

    public void setMessageFrom(Teacher messageFrom) {
        this.messageFrom = messageFrom;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "message_to")
    public Student getMessageTo() {
        return this.messageTo;
    }

    public void setMessageTo(Student messageTo) {
        this.messageTo = messageTo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "sendtime", length = 10)
    public Date getSendtime() {
        return this.sendtime;
    }

    public void setSendtime(Date sendtime) {
        this.sendtime = sendtime;
    }

    @Column(name = "status", length = 20)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

}
