package model;
// Generated Sep 6, 2020 12:05:52 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Courses generated by hbm2java
 */
@Entity
@Table(name = "my_courses",
        catalog = "onlineschooldb"
)
public class MyCourses implements java.io.Serializable {

    private Integer id;
    private Student student;
    private Courses courses;
    private String status;

    public MyCourses() {
    }

    public MyCourses(Student student, Courses courses, String status) {
        this.student = student;
        this.courses = courses;
        this.status = status;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "student_id")
    public Student getStudent() {
        return student;
    }

    public void setStudent(Student student) {
        this.student = student;
    }
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "course_id")
    public Courses getCourses() {
        return courses;
    }

    public void setCourses(Courses courses) {
        this.courses = courses;
    }


    @Column(name = "status", length = 100)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

}
