package model;
// Generated Sep 6, 2020 12:05:52 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "student",
         catalog = "onlineschooldb"
)
public class Student implements java.io.Serializable {

    private Integer id;
    private User user;
    private String firstName;
    private String lastName;
    private String degree;
    private String institude;
    private String image;
    private String subject;

    public Student() {
    }

    public Student(User user, String firstName, String lastName, String degree, String institude, String image, String subject) {
        this.user = user;
        this.firstName = firstName;
        this.lastName = lastName;
        this.degree = degree;
        this.institude = institude;
        this.image = image;
        this.subject = subject;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "user_id")
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    @Column(name = "first_name", length = 100)
    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @Column(name = "last_name", length = 100)
    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @Column(name = "degree", length = 100)
    public String getDegree() {
        return this.degree;
    }

    public void setDegree(String degree) {
        this.degree = degree;
    }

    @Column(name = "institude", length = 100)
    public String getInstitude() {
        return this.institude;
    }

    public void setInstitude(String institude) {
        this.institude = institude;
    }

    @Column(name = "image", length = 100)
    public String getImage() {
        return this.image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    @Column(name = "subject", length = 100)
    public String getSubject() {
        return this.subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

}
