package model;
// Generated Sep 6, 2020 12:05:52 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Teacher generated by hbm2java
 */
@Entity
@Table(name = "teacher",
        catalog = "onlineschooldb"
)
public class Teacher implements java.io.Serializable {

    private Integer id;
    private User user;
    private String firstName;
    private String lastName;
    private String occupation;
    private String institude;
    private String designation;
    private String details;
    private String image;

    public Teacher() {
    }

    public Teacher(User user, String firstName, String lastName, String occupation, String institude, String designation, String details, String image) {
        this.user = user;
        this.firstName = firstName;
        this.lastName = lastName;
        this.occupation = occupation;
        this.institude = institude;
        this.designation = designation;
        this.details = details;
        this.image = image;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "user_id")
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    @Column(name = "first_name", length = 100)
    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @Column(name = "last_name", length = 100)
    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @Column(name = "occupation", length = 100)
    public String getOccupation() {
        return this.occupation;
    }

    public void setOccupation(String occupation) {
        this.occupation = occupation;
    }

    @Column(name = "institude")
    public String getInstitude() {
        return this.institude;
    }

    public void setInstitude(String institude) {
        this.institude = institude;
    }

    @Column(name = "designation", length = 100)
    public String getDesignation() {
        return this.designation;
    }

    public void setDesignation(String designation) {
        this.designation = designation;
    }

    @Column(name = "details")
    public String getDetails() {
        return details;
    }

    public void setDetails(String details) {
        this.details = details;
    }

    @Column(name = "image", length = 100)
    public String getImage() {
        return this.image;
    }

    public void setImage(String image) {
        this.image = image;
    }

}